"""Reachability on sampled actual terrain, not gameplay navigation or building placement."""
import base64
import heapq
import json
import math
import hashlib
from pathlib import Path

HERE=Path(__file__).resolve().parent
world=json.loads((HERE/'round3_world_seed.json').read_text(encoding='utf-8'))
n=world['grid_size']; cell=world['cell_m']; grid=base64.b64decode(world['walkable_base64'])
origin=tuple(world['spawn'])
def center(idx):
    return ((idx%n+.5)*cell,(idx//n+.5)*cell)
def neighborhood(point,radius):
    xx,zz=(int(p/cell) for p in point)
    reach=math.ceil(radius/cell)
    for z in range(max(0,zz-reach),min(n,zz+reach+1)):
        for x in range(max(0,xx-reach),min(n,xx+reach+1)):
            idx=z*n+x
            if grid[idx] and math.dist(center(idx),point)<=radius:
                yield idx
starts=list(neighborhood(origin,8))
assert starts, 'No nearby traversable spawn grid; cannot validate this seed'
start=min(starts,key=lambda idx:math.dist(center(idx),origin))
distance=[math.inf]*(n*n);parent=[-1]*(n*n)
distance[start]=math.dist(center(start),origin); todo=[(distance[start],start)]
directions=[(dx,dz) for dx in (-1,0,1) for dz in (-1,0,1) if dx or dz]
while todo:
    length,idx=heapq.heappop(todo)
    if length!=distance[idx]:continue
    x,z=idx%n,idx//n
    for dx,dz in directions:
        nx,nz=x+dx,z+dz
        if not(0<=nx<n and 0<=nz<n):continue
        nxt=nz*n+nx
        if not grid[nxt]:continue
        if dx and dz and not(grid[z*n+nx] and grid[nz*n+x]):continue
        cost=cell*math.hypot(dx,dz); new=length+cost
        if new<distance[nxt]:
            distance[nxt]=new;parent[nxt]=idx;heapq.heappush(todo,(new,nxt))
resources=[]
for dep in world['deposits']:
    point=(dep['x']+.5,dep['z']+.5)
    choices=[idx for idx in neighborhood(point,min(dep['radius'],12)) if math.isfinite(distance[idx])]
    endpoint=min(choices,key=lambda idx:distance[idx]) if choices else None
    resources.append({**dep,'offset_from_spawn':[round(point[i]-origin[i],2) for i in range(2)],
                      'straight_distance_m':round(math.dist(origin,point),2),
                      'grid_access_path_m':round(distance[endpoint],2) if endpoint is not None else None,
                      'access_point':[round(v,2) for v in center(endpoint)] if endpoint is not None else None,
                      'buildable_verified':False})

# Fixed candidate camp locations projected onto a small dry neighborhood of the actual seed.
desired=[(350,0),(450,100),(550,0),(450,-100)]
camps=[]
for offset in desired:
    point=tuple(origin[i]+offset[i] for i in range(2))
    choices=[idx for idx in neighborhood(point,12) if math.isfinite(distance[idx])]
    endpoint=min(choices,key=lambda idx:math.dist(center(idx),point)) if choices else None
    actual=center(endpoint) if endpoint is not None else None
    camps.append({'desired_offset':offset,'actual_point':actual,
                  'offset_from_spawn':[round(actual[i]-origin[i],2) for i in range(2)] if actual else None,
                  'straight_from_spawn_m':round(math.dist(actual,origin),2) if actual else None,
                  'grid_path_from_spawn_m':round(distance[endpoint],2) if endpoint is not None else None,
                  'placement_verified':False})
result={'seed':world['seed'],'actual_generator_used':True,'unit_navigation_verified':False,
        'cell_m':cell,'origin':origin,'spawn_grid_snap_m':round(distance[start],2),
        'reachable_cell_count':sum(math.isfinite(d) for d in distance),
        'method':world['grid_rule']+'; 8-neighbor Dijkstra, disallow diagonal corner cutting',
        'limitations':['not Godot unit navigation, structure collision, foliage collision, or foundation suitability',
                       'camp positions are candidate placements; camps are not generated by current game code'],
        'resources':sorted(resources,key=lambda r:r['grid_access_path_m'] if r['grid_access_path_m'] is not None else math.inf),
        'four_camp_candidate':camps}
code_root=HERE.parents[3]/'AlienFrontier'
result['source_sha256']={name:hashlib.sha256((code_root/name).read_bytes()).hexdigest()
                         for name in ('scripts/world/world_generator.gd','scripts/world/world_config.gd',
                                      'scripts/world/world_data.gd','scripts/world/resource_generator.gd')}
near_iron=[r for r in resources if r['kind']==0 and r['straight_distance_m']<=200]
result['starter_iron_candidate_grid_check']={'generated_near_iron_count':len(near_iron),
    'reachable_near_iron_count':sum(r['grid_access_path_m'] is not None for r in near_iron),
    'passes_candidate_grid_rule':any(r['grid_access_path_m'] is not None for r in near_iron),
    'this_is_not_engine_navigation_verdict':True}
(HERE/'round3_map_results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'seed':result['seed'],'reachable_cells':result['reachable_cell_count'],
                  'resource_kind_summary':[{ 'kind':k,'reachable':sum(r['kind']==k and r['grid_access_path_m'] is not None for r in resources)} for k in sorted({r['kind'] for r in resources})],
                  'candidate_camps':camps},ensure_ascii=False))
